version: '3'

services:
  web:
    build:
      context: ./labhouse
      dockerfile: Dockerfile
    command: 
      - /bin/sh
      - -c
      - | 
        python manage.py makemigrations # We run migrations when the database is ready.
        python manage.py migrate --settings=labhouse.settings
        gunicorn labhouse.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/labhouse
      - shared_volume:/app/frontend/static
      - temp_volume:/app/media/
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - API_URL=localhost
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - POSTGRES_DB=labhousedb
      - POSTGRES_USER=labhouse
      - POSTGRES_PASSWORD=labhouse
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - STABILITY_API_KEY 
    
  nginx:
    build:  
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - shared_volume:/labhouse/labhouse/frontend/static
    depends_on:
      - web

  celery:
    build:
      context: ./labhouse
      dockerfile: Dockerfile
    command: celery -A labhouse worker -l INFO
    volumes:
      - .:/labhouse
      - temp_volume:/app/media/
    depends_on:
      - web
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - POSTGRES_DB=labhousedb
      - POSTGRES_USER=labhouse
      - POSTGRES_PASSWORD=labhouse
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432 
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=labhousedb
      - POSTGRES_USER=labhouse
      - POSTGRES_PASSWORD=labhouse
    volumes:
      - ./data/db:/var/lib/postgresql/data


  redis:
    image: redis:latest
    ports:
      - 6379:6379
  
volumes:
  shared_volume: 
  temp_volume:
